language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  
# command to install dependencies
install: 
  - pip install dateutil
  - pip install requests
  - pip install trakt.py
# command to run tests
script: python -m unittest discover

